import { CountryCode, CountryProfile, Etape, Guide, Materiau, Piece, Question, WorkType } from './models';

export const COUNTRIES: CountryProfile[] = [
  {code:'FR',nom:'France',drapeau:'🇫🇷',devise:'€',contexte:[
    'En copropriété, vérifier le règlement et les autorisations avant de toucher aux parties communes, façades ou réseaux collectifs.',
    'Demander les qualifications, assurances et attestations adaptées aux travaux avant l’ouverture du chantier.',
    'Dans un bâtiment ancien, consulter les diagnostics amiante et plomb avant perçage, ponçage ou dépose.'
  ],sources:[
    {organisme:'Service-Public.fr',label:'Travaux en copropriété',url:'https://www.service-public.fr/particuliers/vosdroits/F31513'},
    {organisme:'France Rénov’',label:'Ventilation du logement',url:'https://france-renov.gouv.fr/renovation/vmc'},
    {organisme:'Service-Public.fr',label:'Aides à la rénovation',url:'https://www.service-public.fr/particuliers/vosdroits/F1328'}
  ]},
  {code:'MA',nom:'Maroc',drapeau:'🇲🇦',devise:'MAD',contexte:[
    'Adapter les produits au climat local : humidité littorale, chaleur, UV et écarts thermiques selon la ville et l’exposition.',
    'Demander les références des produits et vérifier les normes marocaines applicables au lieu de supposer qu’une norme étrangère suffit.',
    'Faire préciser par écrit le périmètre, les quantités, les marques, les délais et la responsabilité de chaque intervenant.'
  ],sources:[
    {organisme:'Ministère de l’Industrie et du Commerce',label:'Normes marocaines obligatoires — mise à jour 2026',url:'https://www.mcinet.gov.ma/sites/default/files/liste%20NMO%20et%20reglementation%20technique%20V%2009-03-2026.pdf'},
    {organisme:'Ministère de l’Industrie et du Commerce',label:'Sécurité des produits',url:'https://www.mcinet.gov.ma/fr/content/qualite-et-surveillance-des-marches/surveillance-du-march%C3%A9'},
    {organisme:'AMEE',label:'Efficacité énergétique des bâtiments',url:'https://amee.ma/'}
  ]}
];

export const WORKS: WorkType[] = [
  {code:'carrelage',nom:'Carrelage',icon:'▦',description:'Choix, préparation, pose et joints'},
  {code:'plomberie',nom:'Plomberie',icon:'◉',description:'Réseaux, évacuations et équipements'},
  {code:'peinture',nom:'Peinture',icon:'◒',description:'Diagnostic, préparation et finitions'},
  {code:'electricite',nom:'Électricité',icon:'ϟ',description:'Circuits, protections et contrôles'},
  {code:'ventilation',nom:'Ventilation',icon:'≋',description:'Renouvellement d’air et humidité'},
  {code:'etancheite',nom:'Étanchéité',icon:'◇',description:'Supports, membranes et points singuliers'},
  {code:'revetement-sol',nom:'Revêtement de sol',icon:'▤',description:'Parquet, stratifié, vinyle et préparation'}
];

export const PIECES: Piece[] = [
  {code:'salle-de-bain',nom:'Salle de bain',icon:'♨',description:'Zone humide, réseaux et finitions techniques',travaux:['carrelage','plomberie','electricite','ventilation','etancheite']},
  {code:'cuisine',nom:'Cuisine',icon:'⌂',description:'Réseaux, murs et équipements sollicités',travaux:['carrelage','plomberie','peinture','electricite','ventilation','revetement-sol']},
  {code:'piece-de-vie',nom:'Salon & chambre',icon:'□',description:'Confort, décoration et qualité de l’air',travaux:['peinture','electricite','ventilation','revetement-sol']},
  {code:'terrasse',nom:'Terrasse & balcon',icon:'☀',description:'Eau, soleil et variations de température',travaux:['carrelage','etancheite','electricite']}
];

const opts=(v:Array<[string,string]>)=>v.map(([code,libelle])=>({code,libelle}));
const support:Question={code:'support',libelle:'Quel est l’état du support ?',aide:'Choisissez « Je ne sais pas » si aucun diagnostic n’a été réalisé.',options:opts([['neuf','Neuf'],['bon','Existant en bon état'],['degrade','Dégradé ou humide'],['inconnu','Je ne sais pas']])};
const QUESTIONS:Record<string,Question[]>={
  carrelage:[support,{code:'zone',libelle:'Quelle zone sera carrelée ?',options:opts([['sol','Sol'],['mur','Murs'],['les-deux','Sol et murs'],['exterieur','Extérieur']])},{code:'depose',libelle:'Faut-il retirer un revêtement existant ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])},{code:'eau',libelle:'La zone reçoit-elle directement de l’eau ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])}],
  plomberie:[{code:'ampleur',libelle:'Quelle est l’ampleur des travaux ?',options:opts([['equipement','Remplacer un équipement'],['reseau','Modifier les réseaux'],['complet','Rénovation complète'],['inconnu','Je ne sais pas']])},support],
  peinture:[support,{code:'humidite',libelle:'Voyez-vous humidité, cloques ou moisissures ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])},{code:'finition',libelle:'Quel rendu recherchez-vous ?',options:opts([['mat','Mat'],['velours','Velours'],['satin','Satin / lessivable'],['inconnu','Je ne sais pas']])}],
  electricite:[{code:'ampleur',libelle:'Quelle est l’ampleur des travaux ?',options:opts([['appareillage','Prises ou éclairage'],['partiel','Rénovation partielle'],['complet','Rénovation complète'],['inconnu','Je ne sais pas']])},{code:'zoneHumide',libelle:'Les travaux sont-ils dans une zone humide ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])},{code:'tableau',libelle:'Le tableau doit-il être modifié ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','À diagnostiquer']])}],
  ventilation:[{code:'symptome',libelle:'Quel problème observez-vous ?',options:opts([['condensation','Condensation'],['odeur','Odeurs persistantes'],['moisissure','Moisissures'],['projet','Amélioration préventive']])},{code:'systeme',libelle:'Quel système existe actuellement ?',options:opts([['naturelle','Ventilation naturelle'],['mecanique','Extraction mécanique / VMC'],['aucun','Aucun identifié'],['inconnu','Je ne sais pas']])}],
  etancheite:[support,{code:'infiltration',libelle:'Une infiltration est-elle visible ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])},{code:'protection',libelle:'Quelle finition est prévue ?',options:opts([['carrelage','Carrelage'],['dalle','Dalles ou protection lourde'],['apparente','Système apparent'],['inconnu','Je ne sais pas']])}],
  'revetement-sol':[support,{code:'materiau',libelle:'Quel revêtement envisagez-vous ?',options:opts([['parquet','Parquet'],['stratifie','Stratifié'],['vinyle','Vinyle / PVC'],['inconnu','Je compare encore']])},{code:'chauffageSol',libelle:'Y a-t-il un chauffage au sol ?',options:opts([['oui','Oui'],['non','Non'],['inconnu','Je ne sais pas']])}]
};

const mat=(code:string,nom:string,description:string,usages:string,entretien:string,resistance:string,pose:string,prix:string,avantages:string[],inconvenients:string[]):Materiau=>({code,nom,description,usages,entretien,resistance,difficultePose:pose,niveauPrix:prix,avantages,inconvenients});
const MATERIALS:Record<string,Materiau[]>={
  carrelage:[mat('gres','Grès cérame','Dense et polyvalent ; vérifier la destination exacte du modèle.','Sol, mur, parfois extérieur','Facile','Élevée','Moyenne','€€',['Résistant','Nombreux formats'],['Découpe exigeante en grand format']),mat('faience','Faïence','Revêtement décoratif principalement mural.','Mur intérieur','Facile','Moyenne','Moyenne','€€',['Décorative'],['Généralement inadaptée au sol']),mat('mosaique','Mosaïque','Petits éléments adaptés aux formes et à certaines pentes.','Mur et sols compatibles','Joints nombreux','Variable','Élevée','€€€',['Suit les formes'],['Pose minutieuse'])],
  peinture:[mat('acrylique','Peinture acrylique','Peinture en phase aqueuse courante pour murs et plafonds.','Intérieur selon gamme','Selon finition','Variable','Moyenne','€€',['Faible odeur','Séchage rapide'],['Support bien préparé nécessaire']),mat('velours','Finition velours ou satin','Plus résistante au nettoyage qu’un mat profond.','Pièces sollicitées selon produit','Lessivable selon fiche','Bonne','Moyenne','€€',['Entretien facilité'],['Révèle les défauts'])],
  plomberie:[mat('reseaux','Multicouche, PER ou cuivre','Le choix dépend de l’usage, de l’accessibilité et des règles locales.','Alimentation en eau','Raccords à contrôler','Selon système','Professionnelle','€€',['Plusieurs solutions durables'],['Compatibilité raccord/tube impérative'])],
  electricite:[mat('circuits','Circuits et protections','Sections, disjoncteurs, différentiels et terre forment un système.','Installation électrique','Contrôles nécessaires','Sécurité critique','Professionnelle','€€€',['Sécurité et évolutivité'],['Travaux dangereux'])],
  ventilation:[mat('extraction','Ventilation naturelle ou mécanique','Le système renouvelle l’air sans déplacer l’humidité.','Logement et pièces humides','Bouches et filtres','Usage régulier','Professionnelle','€€',['Réduit humidité et polluants'],['Entretien nécessaire'])],
  etancheite:[mat('systeme','Système d’étanchéité complet','Primaire, membrane, bandes, relevés et évacuations doivent être compatibles.','Douche, terrasse ou balcon selon système','Inspection régulière','Élevée si pose correcte','Élevée','€€€',['Protège le bâti'],['Détails déterminants'])],
  'revetement-sol':[mat('sols','Parquet, stratifié ou vinyle','Choisir selon humidité, trafic, acoustique et support.','Pièces compatibles','Selon matériau','Variable','Moyenne','€€',['Confort et choix'],['Planéité et humidité à contrôler'])]
};

type Seed=[string,string,string,string,string?,Record<string,string[]>?];
const STEPS:Record<string,Seed[]>={
  carrelage:[['diagnostic','Diagnostic du support','Décider avant de poser','Contrôle de la stabilité, planéité, humidité et fissures.','Humidimètre, règle'],['calepinage','Mesures et calepinage','Préparer quantités et rendu','Mesure des surfaces, axes, formats, joints et découpes.','Mètre, laser'],['depose','Protection et dépose','Retirer sans dégrader','Protection puis retrait du revêtement et de l’ancienne colle.','Protection, burineur',{'depose':['oui']}],['reparation','Réparation et planéité','Créer un support sain','Nettoyage, rebouchage et ragréage ou dressage si nécessaire.','Enduit, ragréage'],['etancheite','Protection contre l’eau','Éviter les infiltrations','Système compatible dans les zones exposées ; angles et traversées traités.','Membrane, bandes',{'eau':['oui']}],['sechage','Séchage','Respecter le système','Attente selon support, climat et fiche fabricant.','Fiches techniques'],['pose','Encollage et pose','Obtenir adhérence et régularité','Peigne adapté, simple ou double encollage et contrôles continus.','Mortier-colle, peigne'],['decoupes','Découpes','Soigner les finitions','Découpes propres aux angles, seuils et équipements.','Coupe-carreaux, EPI'],['joints','Joints rigides et souples','Finir sans bloquer les mouvements','Jointoiement puis joints souples aux changements de plan prévus.','Mortier de joint, mastic'],['reception','Réception','Valider avant usage','Contrôle des pentes, joints, alignements et délais de remise en service.','Fiche de réception']],
  plomberie:[['diagnostic','Diagnostic des réseaux','Connaître l’existant','Repérage des arrivées, évacuations, vannes, pression et matériaux.','Manomètre'],['plan','Plan d’implantation','Éviter les conflits','Validation des hauteurs, axes, pentes et accès de maintenance.','Plan coté'],['coupure','Coupure et protection','Travailler en sécurité','Coupure de l’eau, vidange et protection des zones conservées.','Vannes, protections'],['reseaux','Alimentations','Distribuer sans fuite','Tubes, raccords et fixations compatibles avec organes accessibles.','Tubes, raccords'],['evacuation','Évacuations','Assurer l’écoulement','Diamètres, pentes, assemblages et ventilation sont vérifiés.','Tubes, niveau'],['essais','Essais avant fermeture','Détecter les défauts','Mise sous pression et contrôle des raccords avant habillage.','Manomètre, bouchons'],['equipements','Pose des équipements','Rendre utilisable','Pose, réglage et étanchéité des raccordements.','Robinetterie, siphons'],['reception','Mise en service','Valider le fonctionnement','Contrôle des fuites, températures, débits, bruits et évacuations.','Fiche de réception']],
  peinture:[['diagnostic','Diagnostic du support','Traiter la cause','Recherche d’humidité, farinage, cloques, fissures et anciennes finitions.','Lampe, test adhérence'],['humidite','Traitement de l’humidité','Supprimer la cause','Fuite, infiltration ou condensation se traite avant la peinture.','Diagnostic',{'humidite':['oui']}],['protection','Protection','Préserver la pièce','Protection des sols, prises et menuiseries.','Bâches, ruban'],['nettoyage','Nettoyage','Obtenir un fond propre','Dégraissage adapté, rinçage si nécessaire et séchage.','Nettoyant'],['reparation','Rebouchage et enduit','Corriger les défauts','Rebouchage, enduit puis respect du séchage.','Enduit, couteaux'],['poncage','Ponçage et dépoussiérage','Uniformiser','Ponçage avec aspiration et contrôle en lumière rasante.','Abrasifs, EPI'],['primaire','Impression adaptée','Réguler l’absorption','Sous-couche compatible avec le fond et la finition.','Primaire'],['finition','Couches de finition','Obtenir teinte et résistance','Application régulière et temps entre couches respecté.','Peinture, rouleaux'],['reception','Réception','Valider le rendu','Contrôle après séchage en lumière normale.','Éclairage normal']],
  electricite:[['diagnostic','Diagnostic électrique','Définir l’intervention','Repérage du tableau, terre, protections, circuits et anomalies par un professionnel.','Appareils de mesure'],['plan','Plan des usages','Dimensionner','Position des prises, éclairages et appareils spécialisés.','Plan coté'],['consignation','Mise hors tension','Supprimer le risque','Coupure et vérification d’absence de tension.','VAT, EPI'],['chemins','Cheminements','Protéger les conducteurs','Gaines et boîtes posées en évitant structure et réseaux d’eau.','Gaines, boîtes'],['circuits','Circuits','Associer usage et protection','Conducteurs, sections, couleurs et protections cohérents.','Conducteurs'],['tableau','Tableau et protections','Protéger personnes et biens','Différentiels, disjoncteurs et repérage des circuits.','Tableau',{'tableau':['oui']}],['zone','Zone humide','Tenir compte de l’eau','Implantation et protections vérifiées selon les règles nationales.','Matériel compatible',{'zoneHumide':['oui']}],['essais','Essais et mesures','Prouver la sécurité','Continuité, isolement, terre et protections testés avant remise sous tension.','Contrôleur'],['reception','Remise en service','Transmettre une installation lisible','Étiquetage, explications et remise des documents.','Dossier de réception']],
  ventilation:[['diagnostic','Diagnostic air et humidité','Identifier la cause','Contrôle des entrées, bouches, conduits, débits et sources d’humidité.','Mesure de débit'],['strategie','Parcours de l’air','Organiser le renouvellement','Entrée dans les pièces principales et extraction des pièces humides.','Schéma'],['dimensionnement','Dimensionnement','Éviter bruit et inefficacité','Débits, diamètres, coudes et rejet extérieur étudiés.','Calcul, notices'],['pose','Pose du réseau','Limiter les pertes','Conduits fixés, raccords étanches et accès pour entretien.','Conduits, colliers'],['transfert','Entrées et transfert','Permettre la circulation','Entrées d’air et passages entre pièces vérifiés.','Grilles'],['essais','Mise en service','Vérifier réellement','Mesure des débits, sens de circulation, bruit et réglages.','Anémomètre'],['entretien','Entretien','Conserver les performances','Plan de nettoyage des bouches et filtres.','Notice']],
  etancheite:[['diagnostic','Recherche de la cause','Ne pas masquer','Inspection des fissures, pentes, évacuations, relevés et joints.','Inspection'],['sondage','Sondages ciblés','Délimiter les dégâts','Dépose localisée pour examiner les couches et l’humidité.','Outils de sondage',{'infiltration':['oui']}],['support','Préparation','Créer une base stable','Nettoyage, séchage, réparation et formes de pente.','Mortier réparation'],['primaire','Primaire','Assurer la compatibilité','Application du primaire prévu par le système.','Primaire'],['membrane','Membrane','Créer la barrière','Épaisseur, couches ou recouvrements contrôlés.','Membrane'],['details','Points singuliers','Traiter les risques','Angles, seuils, traversées, évacuations et relevés.','Bandes, manchettes'],['controle','Contrôle avant protection','Corriger tant que visible','Inspection de continuité et essai adapté au système.','Fiche contrôle'],['finition','Protection et finition','Éviter la perforation','Finition posée sans endommager l’étanchéité.','Protection compatible'],['reception','Réception','Surveiller dans le temps','Contrôle des évacuations et plan d’inspection.','Carnet entretien']],
  'revetement-sol':[['diagnostic','Diagnostic du support','Mesurer avant de choisir','Planéité, humidité, fissures et chauffage au sol contrôlés.','Règle, humidimètre'],['choix','Choix du revêtement','Adapter à l’usage','Trafic, eau, acoustique, entretien et lumière comparés.','Fiches techniques'],['depose','Dépose','Revenir à une base saine','Retrait de l’ancien sol et des résidus.','Décolleuse'],['preparation','Réparation et ragréage','Obtenir la planéité','Réparation, primaire et ragréage si nécessaire.','Primaire, ragréage'],['souscouche','Sous-couche et périphérie','Gérer acoustique et mouvements','Sous-couche compatible et jeux périphériques anticipés.','Sous-couche, cales'],['acclimatation','Acclimatation','Stabiliser le matériau','Stockage selon les conditions prescrites par le fabricant.','Hygromètre'],['pose','Pose','Respecter le système','Pose collée, flottante ou clouée avec contrôles.','Outils de pose'],['finitions','Plinthes et seuils','Permettre les mouvements','Finitions sans bloquer les jeux nécessaires.','Plinthes, profils'],['reception','Réception','Valider avant usage','Contrôle du rendu, stabilité, joints et consignes.','Notice']]
};

const NOTES:Record<CountryCode,Record<string,string>>={
  FR:{carrelage:'Demander le domaine d’emploi et les documents techniques du système de pose.',plomberie:'En copropriété, repérer les colonnes et organes communs avant modification.',peinture:'Pour un logement ancien, consulter les diagnostics avant ponçage ou décapage.',electricite:'Faire appliquer la norme française en vigueur et les règles des locaux avec baignoire ou douche.',ventilation:'Une rénovation ne doit pas dégrader le renouvellement d’air du logement.',etancheite:'Une intervention sur balcon, dalle ou évacuation commune peut nécessiter une autorisation.','revetement-sol':'Vérifier les exigences acoustiques de la copropriété avant de remplacer le sol.'},
  MA:{carrelage:'À l’extérieur, vérifier adhérence, absorption et tenue aux UV et écarts thermiques.',plomberie:'Vérifier pression, stockage éventuel, qualité des raccords et accessibilité des vannes.',peinture:'Choisir selon humidité littorale, chaleur, poussière et exposition solaire.',electricite:'Demander les références marocaines appliquées, la mise à la terre et les résultats des essais.',ventilation:'Sur le littoral, traiter ensemble ventilation, condensation et corrosion.',etancheite:'Choisir un système adapté aux UV et amplitudes thermiques, surtout en terrasse.','revetement-sol':'Tenir compte de la chaleur, du soleil et de l’humidité littorale.'}
};
const TITLES:Record<string,string>={carrelage:'Réussir un chantier de carrelage',plomberie:'Comprendre une rénovation de plomberie',peinture:'Obtenir une peinture durable',electricite:'Sécuriser une rénovation électrique',ventilation:'Améliorer la ventilation du logement',etancheite:'Traiter durablement l’étanchéité','revetement-sol':'Choisir et poser un revêtement de sol'};
const WARNINGS:Record<string,string>={carrelage:'Le carrelage n’est pas l’étanchéité. Le support et le système sous-jacent déterminent la durabilité.',plomberie:'Une fuite cachée peut endommager le bâti. Tester les réseaux avant fermeture.',peinture:'Une peinture ne corrige jamais la cause d’une humidité ou d’un support instable.',electricite:'Danger électrique : diagnostic, travaux et essais doivent être confiés à une personne compétente.',ventilation:'Ne bouchez pas une entrée d’air ou une extraction sans diagnostic global.',etancheite:'L’étanchéité est un système complet ; un détail négligé peut provoquer une infiltration.','revetement-sol':'Ne pas poser sur un support trop humide ou insuffisamment plan.'};

function makeSteps(work:string,country:CountryCode):Etape[]{return STEPS[work].map(([code,titre,objectif,description,resources='Outillage adapté',visibleWhen],i)=>({code,ordre:i+1,titre,objectif,description,visibleWhen,dureeIndicative:i<2?'30 min à 2 h':'Selon surface, accès et état',tempsAttente:['sechage','primaire','finition','membrane','essais','acclimatation'].includes(code)?'Selon la fiche technique et le climat':'Aucun délai générique',importance:i<4?'ESSENTIEL':'IMPORTANT',produits:[{nom:resources,fonction:'Conserver la référence et vérifier la compatibilité'}],outils:resources.split(', '),controles:['Étape terminée avant recouvrement','Compatibilités vérifiées','Photos prises avant fermeture si utile'],erreursFrequentes:['Masquer un défaut sans traiter sa cause','Raccourcir un délai'],notePays:i===0?NOTES[country][work]:undefined}));}

export function createGuide(country:CountryCode,pieceCode:string,work:string):Guide{
  const piece=PIECES.find(p=>p.code===pieceCode)??PIECES[0];const profile=COUNTRIES.find(p=>p.code===country)??COUNTRIES[0];const label=WORKS.find(w=>w.code===work)?.nom??work;
  return {code:`${country.toLowerCase()}-${piece.code}-${work}`,pieceCode:piece.code,travauxCode:work,titre:TITLES[work],introduction:`Guide ${label.toLowerCase()} pour ${piece.nom.toLowerCase()}, adapté au contexte ${profile.nom}.`,avertissement:WARNINGS[work],pays:country,conseilsPays:[NOTES[country][work],...profile.contexte],questions:QUESTIONS[work],materiaux:MATERIALS[work]??[],etapes:makeSteps(work,country),questionsArtisan:['Quel diagnostic justifie votre solution ?','Quelles références exactes utiliserez-vous ?','Quels supports et produits sont incompatibles ?','Quels contrôles seront faits avant de masquer les travaux ?','Quels délais faut-il respecter ?','Quelles garanties et quels documents remettrez-vous ?'],glossaire:{Support:'Surface ou structure qui reçoit le nouveau système.','Point singulier':'Angle, raccord, traversée ou changement de matériau demandant un traitement spécifique.','Mise en service':'Vérifications réalisées avant l’utilisation normale.','Fiche technique':'Document du fabricant décrivant usages, préparation et limites.'},sources:profile.sources};
}
